andrewauclair/ModernDocking

- docking-ui/src/ModernDocking/ext/ui/DockingUI.java
Update to allow changing the property used for SVG settings icon color in DockingUI.
Fixes #151
> SVG Color Customization

- docking-api/src/ModernDocking/internal/CustomTabbedPane.java
JTabbedPanes now work like they do in IntelliJ. Pressing alt + left will move to the previous tab and wrap around. Pressing alt + right will move to the next tab and wrap around. The JTabbedPane is no longer focusable, which will give focus to the components in the tab.
> JTabbedPane Key Binds

- build.gradle
- docking-api/src/ModernDocking/api/AppStateAPI.java
- docking-api/src/ModernDocking/api/DockingAPI.java
- docking-api/src/ModernDocking/api/LayoutPersistenceAPI.java
- docking-api/src/ModernDocking/exception/DockableNotFoundException.java
- docking-api/src/ModernDocking/exception/DockableRegistrationFailureException.java
- docking-api/src/ModernDocking/exception/RootDockingPanelNotFoundException.java
- docking-api/src/ModernDocking/exception/RootDockingPanelRegistrationFailureException.java
- docking-api/src/ModernDocking/internal/DockingComponentUtils.java
- docking-api/src/ModernDocking/internal/DockingInternal.java
Fixes #174 
- `DockingLayoutException` now specifies the file and state (load or save) that failed.
Fixes #175 
- `DockableNotFoundException` now provides `getPersistentID`
- `DockableRegistrationFailureException` now provides `getPersistentID`
- `DockingLayoutException` now provides `getFile` and `getFailureType`
- `NotDockedException` now provides `getDockable`
Fixes #176 
- `RootDockingPanelRegistrationFailureException` has been added and thrown instead of `DockableRegistrationFailureException` in `Docking.registerDockingPanel`.
- `RootDockingPanelNotFoundException` has been added and thrown instead of `DockableRegistrationFailureException` in `Docking.configurePinning` and `Docking.dock`.
> Fixes for #174, #175 and #176 for exception improvements.

- docking-api/src/ModernDocking/api/AppStateAPI.java
- docking-api/src/ModernDocking/layouts/WindowLayout.java
Fixes #198. Windows will now return to their previous size and location if they were persisted maximized. Normally Java AWT/Swing windows don't retain a size and location. This would result requiring the user to manually adjust the size.
This is achieved by storing the previously persisted layout inside of Modern Docking and moving the location and size of each Window to the new layout if a Window is maximized (i.e. has no location and size in the new layout).
> Windows will now retain their previous size and location if maximized

- docking-api/src/ModernDocking/api/DockingStateAPI.java
- docking-api/src/ModernDocking/internal/DockingInternal.java
> Throwing the correct exceptions.

- docking-api/src/ModernDocking/api/DockingStateAPI.java
- docking-api/src/ModernDocking/persist/RootDockState.java
- docking-single-app/src/ModernDocking/app/DockingState.java
Fixes #194. Deprecating `RootDockingState` for removal after the next release.
> Deprecating `RootDockState` and associated functions for removal.

- .github/workflows/publish.yml
- demo-multi-app/build.gradle
- demo-single-app/build.gradle
- docking-api/src/module-info.java
- docking-multi-app/build.gradle
- docking-single-app/build.gradle
- docking-ui/build.gradle
- package-renamer/docking-api-module-info.java
- package-renamer/docking-multi-app-module-info.java
- package-renamer/docking-single-app-module-info.java
- package-renamer/docking-ui-module-info.java
- package-renamer/src/Main.java
The new package rename step needs to happen in the package action too.
build.gradle files have been updated to allow for building modern docking using the maven central packages instead of the local packages. This can be done as 'gradlew build -PuseMavenVersion=true'.
module-info.java files are now copied by the package renamer because having the new packages directly in the existing module-info.java causes compile issues with a fresh pull of the repo.
> Publish action package rename

- demo-single-app/src/basic/MainFrame.java
- docking-api/src/ModernDocking/api/AppStateAPI.java
Make sure that the main window root panel exists before attempting to persist its layout.
> Issue #230

- README.md
The Modern Docking and Flatlaf badges in the README did not actually link to anything helpful, only the svg.
> Maven central links

- demo-single-app/src/basic/MainFrame.java
- docking-api/src/ModernDocking/Dockable.java
- docking-api/src/ModernDocking/DockableTabPreference.java
- docking-api/src/ModernDocking/api/RootDockingPanelAPI.java
- docking-api/src/ModernDocking/floating/DisplayPanelFloatListener.java
- docking-api/src/ModernDocking/floating/TempFloatingFrame.java
- docking-api/src/ModernDocking/internal/DisplayPanel.java
- docking-api/src/ModernDocking/internal/DockedSimplePanel.java
- docking-api/src/ModernDocking/internal/DockedSplitPanel.java
- docking-api/src/ModernDocking/internal/DockedTabbedPanel.java
- docking-api/src/ModernDocking/layouts/DockingLayoutRootNode.java
- docking-api/src/ModernDocking/layouts/DockingSimplePanelNode.java
- docking-api/src/ModernDocking/layouts/DockingSplitPanelNode.java
- docking-api/src/ModernDocking/layouts/DockingTabPanelNode.java
- docking-api/src/ModernDocking/settings/Settings.java
Replace Settings.alwaysDisplayTabsMode(Dockable) and Settings.setAlwaysDisplayTabMode with Settings.defaultTabPreference and Settings.setDefaultTabPreference.
This new setting makes it possible to specify tab location preference as top or bottom. It also makes it possible to always display tabs by using DockableTabPreference.TOP_ALWAYS and DockableTabPreference.BOTTOM_ALWAYS.
The Dockable.getTabPosition method has been replaced with Dockable.getTabPreference, which now returns an instance of DockableTabPreference and returns NONE by default.
> Improve API for Tab Preference Selection

- docking-api/src/ModernDocking/api/DockingAPI.java
- docking-api/src/ModernDocking/api/DockingStateAPI.java
- docking-api/src/ModernDocking/api/RootDockingPanelAPI.java
- docking-api/src/ModernDocking/floating/DisplayPanelFloatListener.java
- docking-api/src/ModernDocking/floating/FloatListener.java
- docking-api/src/ModernDocking/floating/FloatUtilsFrame.java
- docking-api/src/ModernDocking/floating/Floating.java
- docking-api/src/ModernDocking/floating/FloatingOverlay.java
- docking-api/src/ModernDocking/floating/RootDockingHandles.java
- docking-api/src/ModernDocking/internal/ActiveDockableHighlighter.java
- docking-api/src/ModernDocking/internal/DockableWrapper.java
- docking-api/src/ModernDocking/internal/DockingComponentUtils.java
- docking-api/src/ModernDocking/internal/DockingInternal.java
- docking-api/src/ModernDocking/internal/InternalRootDockingPanel.java
- docking-api/src/ModernDocking/layouts/DockingLayouts.java
- docking-api/src/ModernDocking/persist/RootDockState.java
Creating a new InternalRootDockingPanel and moving most of the methods from RootDockingPanelAPI to it.
RootDockingPanelAPI extends JPanel instead of DockingPanel now.
No deprecation warning is being given for this change because all of these methods were already considered internal, but not explicitly documented as such.
> Hide Internal RootDockingPanel Methods

- docking-api/src/ModernDocking/Property.java
- docking-api/src/ModernDocking/api/LayoutPersistenceAPI.java
- docking-api/src/ModernDocking/api/WindowLayoutBuilderAPI.java
- docking-api/src/ModernDocking/internal/DockableProperties.java
- docking-api/src/ModernDocking/layouts/DockingSimplePanelNode.java
- docking-single-app/src/ModernDocking/app/AppState.java
The new property changes weren't loading old files and weren't reloading new files properly. The name of the property is also now stored in the layout file.
> The property changes for 0.12 caused the properties not save and reload.

- demo-single-app/src/basic/ToolPanel.java
- docking-api/src/ModernDocking/Dockable.java
- docking-api/src/ModernDocking/internal/DockedTabbedPanel.java
- docking-api/src/ModernDocking/ui/HeaderController.java
Adding a `requestClose` callback option to the `Dockable` interface. This method allows an application to confirm that the dockable can be closed. This can be seen in use in the single application demo, `ToolPanel.java` where the user is asked Yes/No when closing the tool panels.
> Issue #244 - Request Close of Dockable.

- build.gradle
- demo-multi-app/build.gradle
- demo-single-app/build.gradle
- docking-ui/build.gradle
The demo projects only need the flatlaf and flatlaf-intellij-themes packages in order to use IntelliJ themes. The flatlaf-extras is no longer needed and svgSalamander was a dependency of an older flatlaf version.
> Dependency Cleanup

- docking-api/src/ModernDocking/api/DockingStateAPI.java
- docking-api/src/ModernDocking/api/LayoutPersistenceAPI.java
- docking-api/src/ModernDocking/internal/DockedTabbedPanel.java
- docking-api/src/ModernDocking/layouts/DockingLayoutRootNode.java
- docking-api/src/ModernDocking/layouts/DockingLayouts.java
- docking-api/src/ModernDocking/layouts/DockingSimplePanelNode.java
- docking-api/src/ModernDocking/layouts/DockingSplitPanelNode.java
- docking-api/src/ModernDocking/layouts/DockingTabPanelNode.java
Dynamic dockables in tab groups now reload properly. This required storing the class-name for the selected tab and all tabs in the group pane. This allows Modern Docking to properly reload. There were also some code changes required to detect when a dockable has failed to load, and to check if it is a dynamic dockable (by attempting to create an instance of the class).
> Issue #196

- demo-single-app/src/basic/MainFrame.java
- docking-api/src/ModernDocking/floating/FloatListener.java
- docking-api/src/ModernDocking/internal/InternalRootDockingPanel.java
The Look and Feel of the empty panel in the root docking panel was not being updated all the time. If the empty panel was not visible, the LAF would remain the same.
I'm not entirely sure if this fixes the issue described, but it could certainly cause it.
> Issue #243

- build.gradle
- docking-api/src/ModernDocking/floating/RootDockingHandles.java
Root center handle is now properly only displayed when the root is empty.
> Issue #262

- docking-api/src/ModernDocking/floating/FloatListener.java
No longer invoking updateFramePosition later. This should prevent a situation when the drag has ended and the floating frame no longer exists. Perhaps it'll smooth out the UI too.
> Issue #265

- docking-multi-app/src/ModernDocking/app/DockableMenuItem.java
- docking-single-app/src/ModernDocking/app/DockableMenuItem.java
DockableMenuItem now catches all exceptions. Issue #272 will make this handling better in the 1.1 release.
> Issue #269

- docking-api/src/ModernDocking/api/DockingStateAPI.java
- docking-api/src/ModernDocking/api/LayoutPersistenceAPI.java
Persistent ID and class-name for tabs and simple panels are now loaded based on name, not index.
When a failed dockable fails to load as a dynamic dockable, the log message is severe and dockable is set to null to force a DockableNotFoundException.
> Issue #268

- docking-api/src/ModernDocking/settings/Settings.java
alwaysDisplayTabsMode and setAlwaysDisplayTabMode should have used TOP_ALWAYS instead of TOP.
When we remove these older functions, we might need to improve the API more to distinguish the uses of TOP_ALWAYS and BOTTOM_ALWAYS vs TOP and BOTTOM. At least document that they are ignored for individual dockables. Those should use TOP and BOTTOM.
> Issue #267

- docking-api/src/ModernDocking/api/DockingAPI.java
- docking-single-app/src/ModernDocking/app/Docking.java
Adding a version of the bringToFront method that takes the dockables persistent ID.
> Issue #266

- demo-single-app/src/basic/MainFrame.java
- docking-api/src/ModernDocking/internal/DockingInternal.java
- docking-multi-app/src/ModernDocking/app/DockableMenuItem.java
- docking-multi-app/src/module-info.java
- docking-single-app/src/ModernDocking/app/DockableMenuItem.java
- docking-single-app/src/module-info.java
Improving error handling in DockableMenuItem. Unfortunately this required adding java.logging as a required module. That's not exactly a patch fix, but it should have been there anyways and it's part of Java, so not a big deal.
> Issue #272

- build.gradle
- docking-api/src/ModernDocking/api/DockingAPI.java
- docking-api/src/ModernDocking/ui/DefaultDockingPanel.java
- docking-single-app/src/ModernDocking/app/Docking.java
`DefaultDockingPanel.isLimitedToRoot` and `DefaultDockingPanel.setLimitedToRoot` should have been deprecated and now are. The new, missing, versions have also been added: `DefaultDockingPanel.isLimitedToWindow` and `DefaultDockingPanel.setLimitedToWindow`.
The single-app version of `Docking` contained a missing deprecation. `Docking.configurePinning` should have been deprecated and now is. `Docking.configureAutoHide` has been added to replace it and call the `DockingAPI.configureAutoHide` method.
`DockingAPI.autoHideAllowed` has been deprecated in favor of a properly named method `DockingAPI.isAutoHideAllowed`. These have both been added to the single-app `Docking` class. `Docking.autoHideAllowed` has been properly marked as deprecated.
These changes will be released in 0.12.1 and 1.0.1 …
> Deprecation fixes and 1.0.1

- docking-api/src/ModernDocking/api/DockingStateAPI.java
When the default tab preference is `TOP_ALWAYS`, simple panels are now restored as tabbed panels with a single top tab.
> Issue #283 - Restoring Simple Panels as Tabbed Panels with TOP_ALWAYS Tab Preference

- build.gradle
- docking-api/src/ModernDocking/api/DockingStateAPI.java
- docking-api/src/ModernDocking/persist/DockableState.java
- docking-api/src/ModernDocking/persist/PanelState.java
- docking-api/src/ModernDocking/persist/SplitState.java
- docking-api/src/ModernDocking/persist/TabState.java
DockableState, PanelState, SplitState, and TabbedState should have deprecated as part of #194.
> Some Docking States Classes Should Have Been Deprecated and Were Missed

- docking-api/src/ModernDocking/Dockable.java
- docking-api/src/ModernDocking/api/DockingAPI.java
- docking-api/src/ModernDocking/ui/HeaderModel.java
- docking-single-app/src/ModernDocking/app/Docking.java
`Docking.pinDockable` and `Docking.unpinDockable` should have been deprecated and replaced with `Docking.autoShowDockable` and `Docking.autoHideDockable`.
Deprecating `Dockable.getHasMoreOptions` in favor of `Dockable.hasMoreMenuOptions`.
> More deprecations

- build.gradle
- docking-api/src/ModernDocking/api/DockingAPI.java
The two base `Docking.dock` methods will silently undock the dockable if it is already docked. This had the potential to leave an empty frame. This PR resolves the issue by disposing of the frame if it is empty.
> Dispose of Frame if the Undock Operation Inside Dock Removes the Last Dockable

- docking-api/src/io/github/andrewauclair/moderndocking/floating/FloatListener.java
- docking-api/src/io/github/andrewauclair/moderndocking/floating/FloatUtilsFrame.java
- docking-api/src/io/github/andrewauclair/moderndocking/floating/FloatingOverlay.java
This PR addresses four issues:
1. The GUI no longer flickers on Linux while dragging dockables
2. Dragging a single dockable out of a frame (where the frame only contains that one dockable) wasn't dragging properly
3. Removed a print statement left in from previous debugging
4. The overlay drawing for the north of a dockable was half the height it should be
> Fix Linux Flicker Issue While Docking, Dragging Single Dockable from Frame, Removing Print Statement, and Fixing Overlay North Size

- README.md
- Writerside/project.ihp
- build.gradle
- demo-single-app/src/basic/MainFrame.java
- docking-api/build.gradle
- docking-multi-app/build.gradle
- docking-single-app/build.gradle
- docking-ui/build.gradle
After this PR is merged, any SNAPSHOT releases will be available from `https://central.sonatype.com/repository/maven-snapshots/` instead of `https://s01.oss.sonatype.org/content/repositories/snapshots/`.
> Central Portal Migration
