demo/src/basic/MainFrame.java, docking-ui/build.gradle, docking-ui/src/docking/ui/FlatLafHeaderUI.java, docking/build.gradle, docking/src/ModernDocking/Docking.java, docking/src/ModernDocking/DockingState.java, docking/src/ModernDocking/internal/FailedDockable.java, docking/src/ModernDocking/layouts/ApplicationLayoutXML.java, docking/src/ModernDocking/layouts/DockingLayoutRootNode.java, docking/src/ModernDocking/layouts/DockingLayouts.java, docking/src/ModernDocking/layouts/DockingSimplePanelNode.java, docking/src/ModernDocking/layouts/DockingSplitPanelNode.java, docking/src/ModernDocking/layouts/DockingTabPanelNode.java, docking/src/ModernDocking/layouts/WindowLayoutXML.java, docking/src/ModernDocking/persist/PanelState.java, docking/src/ModernDocking/persist/RootDockState.java, docking/src/ModernDocking/persist/SplitState.java, docking/src/ModernDocking/ui/DefaultHeaderUI.java
=> Dynamic dockable

README.md, demo/src/basic/MainFrame.java, demo/src/basic/OutputPanel.java, demo/src/basic/SimplePanel.java, docking-ui/src/docking/ui/DockingUI.java, docking/src/ModernDocking/Dockable.java, docking/src/ModernDocking/Docking.java, docking/src/ModernDocking/DockingProperty.java, docking/src/ModernDocking/DockingState.java, docking/src/ModernDocking/internal/DockableProperties.java, docking/src/ModernDocking/layouts/ApplicationLayoutXML.java, docking/src/ModernDocking/layouts/DockingLayouts.java
Improvements for #50. These changes are experimental and won't be enabled by default for right now. I would like to expand them some, but I want some demo apps first.
=> Improved dockable props

docking-api/build.gradle, docking-single-app/build.gradle, docking-ui/build.gradle
build.gradle files will now use github action secrets.
=> Preparing for actions.

docking-api/src/ModernDocking/api/DockingAPI.java, docking-api/src/ModernDocking/floating/DockingHandles.java, docking-api/src/ModernDocking/floating/DockingOverlay.java, docking-api/src/ModernDocking/floating/DockingUtilsFrame.java, docking-api/src/ModernDocking/floating/DragListener.java, docking-api/src/ModernDocking/floating/FloatListener.java, docking-api/src/ModernDocking/floating/TempFloatingFrame.java, docking-api/src/ModernDocking/internal/DockableWrapper.java, docking-api/src/ModernDocking/internal/DockedSimplePanel.java, docking-api/src/ModernDocking/internal/DockedTabbedPanel.java
Reworked floating to work with panels instead of dockables directly. There is still a good bit to cleanup here, but I'd like to merge this and make a new snapshot build.
=> Floating rework

docking-api/src/ModernDocking/floating/FloatListener.java, docking-api/src/ModernDocking/internal/CustomTabbedPane.java, docking-api/src/ModernDocking/internal/DockedTabbedPanel.java, docking-api/src/ModernDocking/layouts/DockingTabPanelNode.java
Fixing the issue with dragging completely not working.
Fixing some minor UI display issues with the new tab reordering overlay.
=> More Fixes for Floating

docking-api/src/ModernDocking/floating/FloatListener.java, docking-api/src/ModernDocking/internal/DockedTabbedPanel.java
Top tabs can be dragged properly again.
=> Improvements to allow dragging from the top tabs.

docking-api/src/ModernDocking/api/RootDockingPanelAPI.java
Fixing a few issues with exceptions happening when using JFormDesigner with `RootDockingPanelAPI`.
=> 0.10.0 snapshot uncaught exception in removeNotify in JFormDesigner

docking-api/src/ModernDocking/floating/DockingHandles.java, docking-api/src/ModernDocking/floating/DockingUtilsFrame.java
Last set of handle improvements for now.
=> Handle improvements

docking-api/src/ModernDocking/floating/DockingUtilsFrame.java
Waiting until the frame is visible to update the util frame size.
=> Fixes #131

docking-api/src/module-info.java
=> The internal package is now only exported to the other modern docking modules

docking-api/src/module-info.java
=> Moving Classes to Internal Package

docking-api/src/ModernDocking/api/LayoutPersistenceAPI.java, docking-single-app/build.gradle
=> Fixing exception related to aalto-xml usage.

demo-single-app/src/basic/FixedSizePanel.java, demo-single-app/src/basic/IncorrectDynamicDockable.java, demo-single-app/src/basic/MainFrame.java, docking-api/src/ModernDocking/api/DockingAPI.java, docking-api/src/ModernDocking/api/DockingStateAPI.java, docking-api/src/ModernDocking/floating/DockingOverlay.java, docking-api/src/ModernDocking/floating/DockingUtilsFrame.java, docking-api/src/ModernDocking/floating/FloatListener.java, docking-api/src/ModernDocking/internal/CustomTabbedPane.java, docking-api/src/ModernDocking/internal/DockingComponentUtils.java, docking-api/src/ModernDocking/layouts/DockingTabPanelNode.java, docking-single-app/src/ModernDocking/app/Docking.java
The actual 0.11.1 changes (can't use #191 because of the build.gradle version change). The commits have been cherry picked into this branch without the build.gradle change.
=> 0.11.1 fixes

build.gradle, demo-multi-app/build.gradle, demo-single-app/build.gradle, docking-api/build.gradle, docking-multi-app/build.gradle, docking-single-app/build.gradle, docking-ui/build.gradle
=> Flatlaf 3.3

demo-multi-app/build.gradle, demo-single-app/build.gradle, docking-multi-app/build.gradle, docking-single-app/build.gradle, docking-ui/build.gradle
=> Compile Time Dependencies

docking-api/src/ModernDocking/floating/DockingUtilsFrame.java, docking-api/src/ModernDocking/floating/TempFloatingFrame.java
Dispose the DockingUtilsFrame when its parent frame is closed.
Dispose the TempFloatingFrame on close.
=> Issue #223

docking-api/src/ModernDocking/Dockable.java, docking-api/src/ModernDocking/api/DockingAPI.java
Deprecating isLimitedToRoot in favor of isLimitedToWindow.
=> Issue #165

docking-api/src/ModernDocking/api/LayoutPersistenceAPI.java
Added `saveLayoutToOutputStream`, `saveWindowLayoutToOutputStream`, `loadApplicationLayoutFromInputStream`, `loadWindowLayoutFromInputStream` to `LayoutPersistenceAPI` so that library user can choose what type of backend use to store the layout data.
=> Load and save layouts from IO streams.

docking-api/src/ModernDocking/internal/FloatingFrame.java
Inherit the icons from the main frame configured in DockingAPI.
=> Issue #281 - FloatingFrame Icons

docking-api/src/io/github/andrewauclair/moderndocking/api/DockingStateAPI.java
=> Restore Window to First Display if Offscreen
